version: '3.9'
services:
  postgres:
    image: debezium/example-postgres:${DEBEZIUM_VERSION}
    container_name: postgres
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  debezium-server:
    image: debezium/server:${DEBEZIUM_VERSION}
    container_name: debezium-server
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials/service-account.json
    ports:
      - "8080:8080"
    volumes:
      - /your/path/to/service-account.json:/tmp/credentials/service-account.json
      - ./conf:/debezium/conf
