version: '2.1'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     # For local debugging of Main
     # - ADVERTISED_HOST_NAME=192.168.1.3
  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    build:
      context: example-db
    ports:
     - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=debezium --execute \"SELECT 1;\""
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
  connect:
    image: debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_source_connect_configs
     - OFFSET_STORAGE_TOPIC=my_source_connect_offsets
  event-source:
    image: debezium/kstreams-live-update-event-source:${DEBEZIUM_VERSION}
    build:
      context: event-source
    links:
     - mysql
    environment:
     - JAVA_MAIN_CLASS=io.debezium.examples.kstreams.liveupdate.eventsource.Main
    depends_on:
      mysql:
        condition: service_healthy
  aggregator:
    image: debezium/kstreams-aggregator:${DEBEZIUM_VERSION}
    build:
      context: aggregator
    ports:
     - 8079:8079
    links:
     - kafka
    environment:
     - JAVA_APP_JAR=demo-thorntail.jar
     - "JAVA_OPTIONS=-Djava.net.preferIPv4Stack=true -Dswarm.http.port=8079"
     - AB_PROMETHEUS_OFF=true
    depends_on:
     - connect
    command: >
      /bin/bash -c "
        java -jar /deployments/demo-thorntail.jar -Djava.net.preferIPv4Stack=true -Dswarm.http.port=8079
      "
