version: '2.1'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     # For local debugging of Main
     # - ADVERTISED_HOST_NAME=192.168.1.3
  mysql:
    image: debezium-examples/kstreams-live-update-mysql:${DEBEZIUM_VERSION}
    build:
      context: mysql-db
    ports:
     - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=debezium --execute \"SELECT 1;\""
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
  connect:
    image: debezium-examples/kstreams-live-update-connect-es:${DEBEZIUM_VERSION}
    build:
      context: debezium-es
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
     - elastic
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_source_connect_configs
     - OFFSET_STORAGE_TOPIC=my_source_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
  event-source:
    image: debezium-examples/kstreams-live-update-event-source:${DEBEZIUM_VERSION}
    build:
      context: event-source
    links:
     - mysql
    environment:
     - DATABASE_SERVER=mysql 
     - JAVA_MAIN_CLASS=io.debezium.examples.kstreams.liveupdate.eventsource.Main
    depends_on:
      mysql:
        condition: service_healthy
  aggregator:
    image: debezium-examples/kstreams-live-update-aggregator:${DEBEZIUM_VERSION}
    build:
      context: aggregator
    ports:
     - 8079:8079
    links:
     - kafka
    environment:
     - PORT=8079
     - QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
     - connect
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
     - "9200:9200"
    environment:
     - http.host=0.0.0.0
     - transport.host=127.0.0.1
     - xpack.security.enabled=false
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
