version: '2'
services:
  kafka-1:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
     - 19092:9092
     - 19093:9093
     - 9012:9012
    environment:
     - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
     - BROKER_ID=1
     - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093
     - NODE_ROLE=controller
     - JMXPORT=9012
     - JMXHOST=0.0.0.0
  kafka-2:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 29092:9092
      - 29093:9093
      - 9013:9013
    environment:
      - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
      - BROKER_ID=2
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093
      - NODE_ROLE=broker
      - JMXPORT=9013
      - JMXHOST=0.0.0.0
  kafka-3:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 39092:9092
      - 39093:9093
      - 9014:9014
    environment:
      - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
      - BROKER_ID=3
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093
      - NODE_ROLE=broker
      - JMXPORT=9014
      - JMXHOST=0.0.0.0
  kafka-4:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 49092:9092
      - 49093:9093
      - 9015:9015
    environment:
      - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
      - BROKER_ID=4
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093
      - NODE_ROLE=broker
      - JMXPORT=9014
      - JMXHOST=0.0.0.0
  postgres:
    image: quay.io/debezium/example-postgres:${DEBEZIUM_VERSION}
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
      - 8083:8083
    links:
      - kafka-1
      - kafka-2
      - kafka-3
      - kafka-4
      - postgres
    environment:
      - BOOTSTRAP_SERVERS=kafka-2:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
