services:
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
      - NODE_ID=1
      - NODE_ROLE=combined
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

  cassandra:
    image: debezium/example-cassandra:${DEBEZIUM_VERSION}
    build:
      context: ./debezium-cassandra-init
    ports:
      - 9042:9042
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - /var/lib/cassandra
