services:
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
      - NODE_ID=1
      - NODE_ROLE=combined
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

  db2server:
    image: debezium/db2-cdc:${DEBEZIUM_VERSION}
    build:
      context: ./debezium-db2-init/db2server
    privileged: True
    ports:
     - 50000:50000
    environment:
     - LICENSE=accept 
     - DBNAME=TESTDB
     - DB2INST1_PASSWORD==Password!
    volumes: 
     - ./db2data:/database
     
  connect:
    image: debezium/connect-db2:${DEBEZIUM_VERSION}
    build:
      context: ./debezium-db2-init/db2connect
      args:
        DEBEZIUM_VERSION: ${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    depends_on:
     - kafka
     - db2server
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
