version: '2'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  cassandra:
    image: debezium/example-cassandra:${DEBEZIUM_VERSION}
    build:
      context: ./debezium-cassandra-init
    ports:
      - 9042:9042
    links:
      - zookeeper
      - kafka
    volumes:
      - /var/lib/cassandra
