# Copyright Debezium Authors.
#
# Licensed under the Apache License version 2.0, available at
# http://www.apache.org/licenses/LICENSE-2.0

FROM python:3.12-alpine

WORKDIR /app
COPY server.py /app/server.py

CMD ["python", "/app/server.py"]
