services:
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
      - NODE_ID=1
      - NODE_ROLE=combined
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      # For local development of toast-value-store
      # - ADVERTISED_HOST_NAME=192.168.1.4
      - KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS=250

  source-db:
    image: debezium-examples/toast-source-db:${DEBEZIUM_VERSION}
    build:
      context: source-db
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgresusersource
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=sourcedb

  sink-db:
    image: debezium-examples/toast-sink-db:${DEBEZIUM_VERSION}
    build:
      context: sink-db
    ports:
     - "5433:5432"
    environment:
     - POSTGRES_USER=postgresusersink
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=sinkdb

  connect:
    image: debezium-examples/toast-connect:${DEBEZIUM_VERSION}
    build:
      context: debezium-jdbc
    ports:
     - 8083:8083
    depends_on:
     - kafka
     - source-db
     - sink-db
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses

  toast-value-store:
    image: debezium-examples/toast-value-store:${DEBEZIUM_VERSION}
    build:
      context: toast-value-store
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
     - 8080:8080
    depends_on:
     - kafka
    environment:
     - QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS=kafka:9092
