services:
  postgres:
    image: quay.io/debezium/example-postgres:${DEBEZIUM_VERSION}
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - "9092:9092"
  debezium-server:
    image: debezium/debezium-server
    build:
      context: ./server
      args:
        DEBEZIUM_VERSION: ${DEBEZIUM_VERSION}
    ports:
      - "8080:8080"
    volumes:
      - ./config:/debezium/config
    links:
      - kafka
      - postgres