version: '3.9'
services:
  postgres:
    image: quay.io/debezium/example-postgres:${DEBEZIUM_VERSION}
    container_name: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  mongodb:
    image: quay.io/debezium/example-mongodb:${DEBEZIUM_VERSION}
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USER=debezium
      - MONGODB_PASSWORD=dbz
  mysql:
    image: quay.io/debezium/example-mysql:${DEBEZIUM_VERSION}
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  debezium-server-postgres:
    image: quay.io/debezium/server:${DEBEZIUM_VERSION}
    container_name: debezium-server-postgres
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials/service-account.json
    ports:
      - "8080:8080"
    volumes:
      - /your/path/to/service-account.json:/tmp/credentials/service-account.json
      - ./config-postgres:/debezium/conf
  debezium-server-mongodb:
    image: quay.io/debezium/server:${DEBEZIUM_VERSION}
    container_name: debezium-server-mongodb
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials/service-account.json
    ports:
      - "8080:8080"
    volumes:
      - /your/path/to/service-account.json:/tmp/credentials/service-account.json
      - ./config-mongodb:/debezium/conf
  debezium-server-mysql:
    image: quay.io/debezium/server:${DEBEZIUM_VERSION}
    container_name: debezium-server-mysql
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/credentials/service-account.json
    ports:
      - "8080:8080"
    volumes:
      - /your/path/to/service-account.json:/tmp/credentials/service-account.json
      - ./config-mysql:/debezium/conf
