services:
  postgres:
    image: quay.io/debezium/example-postgres:${DEBEZIUM_VERSION}
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -h 127.0.0.1 -U postgresuser -d postgresuser"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespw

  quarkus-native-app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
