apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: debezium-operator-subscription
  namespace: operators
spec:
  installPlanApproval: Automatic
  name: debezium-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  channel: debezium-2.5.x
  startingCSV: debezium-operator.v2.5.0
