ARG STRIMZI_VERSION=latest-kafka-3.4.0
FROM quay.io/strimzi/kafka:${STRIMZI_VERSION}

ARG DEBEZIUM_CONNECTOR_VERSION=2.1.3.Final
ARG OTEL_VERSION=1.23.0

ENV KAFKA_CONNECT_PLUGIN_PATH=/tmp/connect-plugins/
ENV KAFKA_CONNECT_SHARE_JAVA_PATH=/opt/kafka/libs
COPY "debezium-connector-postgres-2.4.0-SNAPSHOT-plugin.tar.gz" /
COPY "debezium-interceptor-otel-2.4.0-SNAPSHOT.jar" $KAFKA_CONNECT_SHARE_JAVA_PATH
USER root

RUN curl -L -o /opt/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v${OTEL_VERSION}/opentelemetry-javaagent.jar
RUN curl -L -o ${KAFKA_CONNECT_SHARE_JAVA_PATH}/opentelemetry-api-${OTEL_VERSION}.jar https://repo1.maven.org/maven2/io/opentelemetry/opentelemetry-api/${OTEL_VERSION}/opentelemetry-api-${OTEL_VERSION}.jar
RUN curl -L -o ${KAFKA_CONNECT_SHARE_JAVA_PATH}/opentelemetry-context-${OTEL_VERSION}.jar https://repo1.maven.org/maven2/io/opentelemetry/opentelemetry-context/${OTEL_VERSION}/opentelemetry-context-${OTEL_VERSION}.jar
RUN curl -L -o ${KAFKA_CONNECT_SHARE_JAVA_PATH}/opentelemetry-instrumentation-api-${OTEL_VERSION}.jar https://repo1.maven.org/maven2/io/opentelemetry/instrumentation/opentelemetry-instrumentation-api/${OTEL_VERSION}/opentelemetry-instrumentation-api-${OTEL_VERSION}.jar
RUN curl -L -o ${KAFKA_CONNECT_SHARE_JAVA_PATH}/opentelemetry-instrumentation-api-semconv-${OTEL_VERSION}-alpha.jar https://repo1.maven.org/maven2/io/opentelemetry/instrumentation/opentelemetry-instrumentation-api-semconv/${OTEL_VERSION}-alpha/opentelemetry-instrumentation-api-semconv-${OTEL_VERSION}-alpha.jar
RUN curl -L -o ${KAFKA_CONNECT_SHARE_JAVA_PATH}/opentelemetry-kafka-clients-2.6-${OTEL_VERSION}-alpha.jar https://repo1.maven.org/maven2/io/opentelemetry/instrumentation/opentelemetry-kafka-clients-2.6/${OTEL_VERSION}-alpha/opentelemetry-kafka-clients-2.6-${OTEL_VERSION}-alpha.jar
RUN curl -L -o ${KAFKA_CONNECT_SHARE_JAVA_PATH}/opentelemetry-kafka-clients-common-${OTEL_VERSION}-alpha.jar https://repo1.maven.org/maven2/io/opentelemetry/instrumentation/opentelemetry-kafka-clients-common/${OTEL_VERSION}-alpha/opentelemetry-kafka-clients-common-${OTEL_VERSION}-alpha.jar
RUN curl -L -o ${KAFKA_CONNECT_SHARE_JAVA_PATH}/opentelemetry-semconv-${OTEL_VERSION}-alpha.jar https://repo1.maven.org/maven2/io/opentelemetry/opentelemetry-semconv/${OTEL_VERSION}-alpha/opentelemetry-semconv-${OTEL_VERSION}-alpha.jar
USER 1001

RUN mkdir $KAFKA_CONNECT_PLUGIN_PATH &&\
    cd $KAFKA_CONNECT_PLUGIN_PATH &&\
    tar xzvf /debezium-connector-postgres-2.4.0-SNAPSHOT-plugin.tar.gz

ENV KAFKA_OPTS="-javaagent:/opt/opentelemetry-javaagent.jar"