version: "3.4"

services:
  mongodb:
    image: debezium/example-mongodb:1.6
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGODB_USER=debezium
      - MONGODB_PASSWORD=dbz