
VALUES ASNCDC.ASNCDCSERVICES('status','asncdc');

CALL ASNCDC.ADDTABLE('DB2INST1', 'PRODUCTS' ); 
CALL ASNCDC.ADDTABLE('DB2INST1', 'PRODUCTS_ON_HAND' ); 
CALL ASNCDC.ADDTABLE('DB2INST1', 'CUSTOMERS' );
CALL ASNCDC.ADDTABLE('DB2INST1', 'ORDERS' ); 

VALUES ASNCDC.ASNCDCSERVICES('reinit','asncdc');