# Quarkus HTTP Port
quarkus.http.port=8080

# Datasource Configuration
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${POSTGRES_USER:postgres}
quarkus.datasource.password=${POSTGRES_PASSWORD:postgres}
quarkus.datasource.jdbc.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:inventory}

# Hibernate ORM & Second-Level Cache
quarkus.hibernate-orm.database.default-schema=inventory
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.second-level-caching-enabled=true
quarkus.hibernate-orm.metrics.enabled=true

# Debezium Engine source connector properties
debezium.source.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.source.database.hostname=${POSTGRES_HOST:localhost}
debezium.source.database.port=5432
debezium.source.database.user=${POSTGRES_USER:postgres}
debezium.source.database.password=${POSTGRES_PASSWORD:postgres}
debezium.source.database.dbname=${POSTGRES_DB:inventory}
debezium.source.topic.prefix=tutorial
debezium.source.table.include.list=inventory.item
debezium.source.plugin.name=pgoutput
debezium.source.schema.history.internal=io.debezium.relational.history.MemorySchemaHistory
debezium.source.offset.storage=org.apache.kafka.connect.storage.MemoryOffsetBackingStore
