FROM fabric8/java-jboss-openjdk8-jdk

# COPY target/kstreams-live-update-aggregator-0.1-SNAPSHOT.jar /deployments
# COPY target/dependencies/* /deployments/
COPY target/demo-thorntail.jar /deployments
