domain:
  url: ""
stage:
  image: quay.io/debezium/platform-stage:nightly
conductor:
  image: quay.io/debezium/platform-conductor:nightly
  offset:
    existingConfigMap: ""
offset:
  reusePlatformDatabase: true
  database:
    name: postgres
    host: postgres
    port: 5432
    username: user
    password: password
    auth:
      existingSecret: ""
schemaHistory:
  reusePlatformDatabase: true
  database:
    name: postgres
    host: postgres
    port: 5432
    username: user
    password: password
    auth:
      existingSecret: ""
database:
  enabled: false
  name: postgres
  host: postgres
  auth:
    existingSecret: ""
env: []