apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
type: Opaque
stringData:
  POSTGRES_USER: debezium
  POSTGRES_PASSWORD: debezium
  POSTGRES_DB: debezium
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: quay.io/debezium/example-postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgresql-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
