apiVersion: v1
kind: Secret
metadata:
  name: postgresql-dest-credentials
type: Opaque
stringData:
  POSTGRES_USER: debezium
  POSTGRES_PASSWORD: debezium
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-dest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-dest
  template:
    metadata:
      labels:
        app: postgresql-dest
    spec:
      containers:
        - name: postgresql
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgresql-dest-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-dest
spec:
  selector:
    app: postgresql-dest
  ports:
    - port: 5432
      targetPort: 5432
