debezium.sink.type=kinesis
debezium.sink.kinesis.region=us-east-1
debezium.source.connector.class=io.debezium.connector.mongodb.MongoDbConnector
debezium.source.tasks.max=1
debezium.source.topic.prefix=tutorial
debezium.source.mongodb.connection.string=mongodb://mongodb:27017/?replicaSet=rs0
debezium.source.mongodb.user=debezium
debezium.source.mongodb.password=dbz
debezium.source.database.include.list=inventory
debezium.source.collection.include.list=inventory.customers
debezium.source.offset.storage.file.filename=/tmp/offsets.dat
debezium.source.offset.flush.interval.ms=0
debezium.format.value=json
debezium.format.value.schemas.enable=false
debezium.format.key=json
debezium.format.key.schemas.enable=false
