{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: debezium-platform
{{ include "common.labels" . | indent 4 }}
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      annotations:
      labels:
        app.kubernetes.io/name: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{ .Values.name }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "database.secretName" . }}
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "database.secretName" . }}
                  key: username
          image: {{ .Values.image }}
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
  {{- end}}