{{- if .Values.enabled -}}
{{- if empty .Values.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
data:
  username: {{ .Values.auth.username | b64enc }}
  password: {{ .Values.auth.password | b64enc }}
{{- end}}
  {{- end}}