services:
  kafka:
    image: quay.io/debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - CLUSTER_ID=oh-sxaDRTcyAr6pFRbXyzA
      - NODE_ID=1
      - NODE_ROLE=combined
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

  primary:
    image: debezium/sql-server-keys
    build:
      context: debezium-sqlserver-init
    hostname: primary
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Enterprise
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true
     - MSSQL_ENABLE_HADR=1

  secondary:
    image: debezium/sql-server-keys
    build:
      context: debezium-sqlserver-init
    hostname: secondary
    ports:
     - 11433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Enterprise
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true
     - MSSQL_ENABLE_HADR=1

  connect:
    image: quay.io/debezium/connect:${DEBEZIUM_VERSION}
    ports:
     - 8083:8083
    depends_on:
     - kafka
     - primary
     - secondary
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
