apiVersion: v1
kind: Template
metadata:
  name: debezium
parameters:
- name: DEBEZIUM_VERSION
  description: A version of Debezium to be included in the image (e.g. 0.6.0)
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: debezium
    name: debezium
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: debezium:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      dockerfile: |
        FROM scholzj/kafka-connect
        ENV KAFKA_CONNECT_PLUGIN_PATH=/opt/debezium \
            DEBEZIUM_VERSION=${DEBEZIUM_VERSION}
        RUN mkdir -p $KAFKA_CONNECT_PLUGIN_PATH && \
            cd $KAFKA_CONNECT_PLUGIN_PATH && \
            for PLUGIN in {mongodb,mysql,postgres}; do \
                curl http://central.maven.org/maven2/io/debezium/debezium-connector-$PLUGIN/$DEBEZIUM_VERSION/debezium-connector-$PLUGIN-$DEBEZIUM_VERSION-plugin.tar.gz | tar xz; \
            done
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: kafka-connect:latest
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: debezium
    name: debezium
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: debezium
    name: kafka-connect
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: scholzj/kafka-connect
