name: Build [cache-invalidation]

on:
  push:
    paths:
      - 'cache-invalidation/**'
      - '.github/workflows/cache-invalidation-workflow.yml'
  pull_request:
    paths:
      - 'cache-invalidation/**'
      - '.github/workflows/cache-invalidation-workflow.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('cache-invalidation/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Check changes in [cache-invalidation] example
        run: cd cache-invalidation && mvn clean package -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
