name: Build [postgres-toast]

on:
  push:
    paths:
      - 'postgres-toast/**'
      - '.github/workflows/postgres-toast-workflow.yml'
      - 'scripts/run-example-test.py'
  pull_request:
    paths:
      - 'postgres-toast/**'
      - '.github/workflows/postgres-toast-workflow.yml'
      - 'scripts/run-example-test.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('postgres-toast/**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check changes in [postgres-toast] example
        run: cd postgres-toast && mvn clean install -f toast-value-store/pom.xml -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install pyyaml requests

      - name: Run postgres-toast test
        run: python scripts/run-example-test.py postgres-toast
